### ISSUE TITLE
package does not work

### ISSUE THREAD

**Issue by wansiedler** [preactjs/preact-custom-element#62]
Hello,
this is my index.js:
```
import register from "preact-custom-element";
import './style';
import App from './components/app';
register(App, "uiwiwidget");
```
template.html:
```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title><% preact.title %></title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<meta name="mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<link rel="apple-touch-icon" href="/assets/icons/apple-touch-icon.png">
		<% preact.headEnd %>
	</head>
	<body>
		<% preact.bodyEnd %>
		<uiwiwidget></uiwiwidget>
	</body>
</html>
```

After yarn run dev or run build nothing happens. Page is empty. What should I do?

**Comment by wansiedler** [comment]
template.html
`<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title><% preact.title %></title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<meta name="mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<link rel="apple-touch-icon" href="/assets/icons/apple-touch-icon.png">
		<% preact.headEnd %>
	</head>
	<body>
		<% preact.bodyEnd %>
		<uiwiwidget></uiwiwidget>
	</body>
</html>
`

**Comment by marvinhagemeister** [comment]
Custom element names require a dash in them. Names without a dash like `uiwiwidget` are therefore not valid. The browser prints this error otherwise:

<img width="892" alt="Screenshot 2021-07-07 at 22 48 40" src="https://user-images.githubusercontent.com/1062408/124827030-d2754300-df75-11eb-839a-2707d1ed932b.png">

To resolve this issue change the custom element name from `<uiwiwidget>` to something like `<x-uiwiwidget>` (best to use your custom prefix instead of `x`).

```diff
  import register from "preact-custom-element";
  import './style';
  import App from './components/app';
- register(App, "uiwiwidget");
+ register(App, "x-uiwiwidget");
```

...and in the HTML

```diff
      <!-- ...snip -->
      <% preact.bodyEnd %>
-     <uiwiwidget></uiwiwidget>
+     <x-uiwiwidget></x-uiwiwidget>
    </body>
  </html>
```

Note that the HTML template is not watched in preact-cli. You might not to either restart the cli all the time or you can render your custom element from Preact in your JSX for a more interactive development setup.
